#pragma once

typedef enum {
    SUCCESS = 0,
    ERROR_INVALID_ARGUMENT,
    ERROR_MEMORY_ALLOCATION,
    ERROR_FILE_OPEN,
    ERROR_FILE_READ,
    ERROR_FILE_WRITE,
    ERROR_INVALID_DATA,
    ERROR_NOT_FOUND,
    ERROR_EMPTY_COLLECTION
} StatusCode;